<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Rhythm</name>
    </assembly>
    <members>
        <member name="T:Rhythm.Revit.ElementFilter.ElementFilter">
            <summary>
            Wrapper class for Element.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.ElementFilter.ElementFilter.ByName(System.Collections.Generic.List{Revit.Elements.Element},System.String,System.String)">
            <summary>
            Provides element filtering options by name. For the filter method, we are using something called "LevenshteinDistance". 
            This was introduced to me by Eric Rudisaile + Kyle Martin here, http://dynamobim.org/fuzzy-string-matching/.
            </summary>
            <param name="elements">The elements to filter.</param>
            <param name="value">The value to filter by.</param>
            <param name="filterMethod">The method to filter by. This includes Contains, DoesNotContain, StartsWith, DoesNotStartWith, EndsWith, DoesNotEndWith, Equals, DoesNotEqual</param>
            <returns name="elements">The filtered elements.</returns>
            <search>
            ElementFilter,Filter.ByName
            </search>
        </member>
        <member name="M:Rhythm.Revit.ElementFilter.ElementFilter.ByParameterStringValue(System.Collections.Generic.List{Revit.Elements.Element},System.String,System.String,System.String)">
            <summary>
            Provides element filtering options by parameter string value. For the filter method, we are using something called "LevenshteinDistance". 
            This was introduced to me by Eric Rudisaile + Kyle Martin here, http://dynamobim.org/fuzzy-string-matching/.
            </summary>
            <param name="elements">The elements to filter.</param>
            <param name="parameterName">The parameter name to filter against..</param>
            <param name="value">The value to filter by.</param>
            <param name="filterMethod">The method to filter by. This includes Contains, DoesNotContain, StartsWith, DoesNotStartWith, EndsWith, DoesNotEndWith, Equals, DoesNotEqual</param>
            <returns name="elements">The filtered elements.</returns>
            <search>
            ElementFilter,Filter.ByName
            </search>
        </member>
        <member name="M:Rhythm.Revit.ElementFilter.ElementFilter.ByParameterNumericValue(System.Collections.Generic.List{Revit.Elements.Element},System.String,System.Double,System.String)">
            <summary>
            Provides element filtering options by parameter numeric value. For the filter method, we are using something called "LevenshteinDistance". 
            This was introduced to me by Eric Rudisaile + Kyle Martin here, http://dynamobim.org/fuzzy-string-matching/.
            </summary>
            <param name="elements">The elements to filter.</param>
            <param name="parameterName">The parameter name to filter against..</param>
            <param name="value">The value to filter by.</param>
            <param name="filterMethod">The method to filter by. This includes GreaterThan, GreaterThanOrEqualTo, LessThan, LessThanOrEqualTo, EqualTo, NotEqualTo</param>
            <returns name="elements">The filtered elements.</returns>
            <search>
            ElementFilter,Filter.ByName
            </search>
        </member>
        <member name="M:Rhythm.Revit.ElementFilter.ElementFilter.ByCategory(System.Collections.Generic.List{Revit.Elements.Element},System.Object,System.String)">
            <summary>
            Provides element filtering options by category. For the filter method, we are using something called "LevenshteinDistance". 
            This was introduced to me by Eric Rudisaile + Kyle Martin here, http://dynamobim.org/fuzzy-string-matching/.
            </summary>
            <param name="elements">The elements to filter.</param>
            <param name="category">The value to filter by.</param>
            <param name="filterMethod">The method to filter by. This includes Contains, DoesNotContain, StartsWith, DoesNotStartWith, EndsWith, DoesNotEndWith, Equals, DoesNotEqual</param>
            <returns name="elements">The filtered elements.</returns>
            <search>
            ElementFilter,Filter.ByName
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Grid">
            <summary>
            Wrapper class for grids.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Grid.GetLeaderEnds(Revit.Elements.Element,Revit.Elements.Views.View)">
            <summary>
            This node will get the underlying curve of the reference plane in a given view.
            </summary>
            <param name="grid">The grid to get leader ends from.</param>
            <param name="view">The view to use.</param>
            <returns name="leaderEnd0">The leader at end 0 (if available).</returns>
            <returns name="leaderEnd1">The leader at end 1 (if available).</returns>
            <search>
            grid.getleaderends
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Category">
            <summary>
            Wrapper class for categories.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Category.ProjectionLineweight(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Get the category projection lineweight.
            </summary>
            <returns name="categoryProjectionLineweight">The category projection lineweights.</returns>
            <search>
            Categories.ProjectionLineweight
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Category.CutLineweight(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Get the category cut lineweight.
            </summary>
            <returns name="categoryCutLineweight">The category projection lineweights.</returns>
            <search>
            Categories.CutLineweight
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Category.LineColor(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Get the category line color as RGB string..
            </summary>
            <returns name="lineColorString">The category line color as a string.</returns>
            <returns name="lineColor">The category line color as a usable Dynamo color.</returns>
            <search>
            Categories.LineColor
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Category.LinePattern(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Get the category line pattern.
            </summary>
            <returns name="linePattern">The category projection line pattern.</returns>
            <search>
            Categories.LinePattern
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Category.Material(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Get the category material and name.
            </summary>
            <returns name="materialName">The category material name.</returns>
            <search>
            Categories.MaterialName
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Wall">
            <summary>
            Wrapper class for walls.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Wall.HasEditedProfile(Revit.Elements.Element)">
            <summary>
            This node will try to check if the walls profile has been modified using logic outlined here,
            http://thebuildingcoder.typepad.com/blog/2010/11/access-to-sketch-and-sketch-plane.html
            </summary>
            <param name="wall">The walls to check.</param>
            <returns name="bool">The result.</returns>
            <search>
            profile, wall
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Wall.EditedProfile(Revit.Elements.Element)">
            <summary>
            This node will try to check if the walls profile has been modified using logic outlined here,
            http://thebuildingcoder.typepad.com/blog/2010/11/access-to-sketch-and-sketch-plane.html
            </summary>
            <param name="wall">The walls to check.</param>
            <returns name="modelCurves">The result.</returns>
            <search>
            profile, wall
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Tag">
            <summary>
            Wrapper class for tag.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.GetHeadPosition(System.Collections.Generic.List{Revit.Elements.Tag})">
            <summary>
            The position of the head of tag in model coordinates (if available).
            </summary>
            <param name="tag">The tag to get head position from.</param>
            <returns name="point">The tag's head position as a point.</returns>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.GetLeaderEnd(System.Collections.Generic.List{Revit.Elements.Tag})">
            <summary>
            The position of the leader end for a tag using free end leader behavior. 
            </summary>
            <param name="tag">The tag to get leader end position from.</param>
            <returns name="point">The tag's leader end position as a point.</returns>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.GetLeaderElbow(System.Collections.Generic.List{Revit.Elements.Tag})">
            <summary>
            The position of the elbow of the tag's leader.  
            </summary>
            <param name="tag">The tag to get leader elbow position from.</param>
            <returns name="point">The tag's leader elbow position as a point.</returns>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.SetLeaderEndPosition(Revit.Elements.Tag,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This will attempt to set the leader end position of the tag.
            </summary>
            <param name="tag">The tag to set leader end position of.</param>
            <param name="location">The new location for the leader end.</param>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.SetHeadPosition(Revit.Elements.Tag,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This will attempt to set the head position of the tag.
            </summary>
            <param name="tag">The tag to set head position of.</param>
            <param name="location">The new location for the head.</param>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Tag.SetLeaderElbowPosition(Revit.Elements.Tag,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This will attempt to set the leader elbow position of the tag.
            </summary>
            <param name="tag">The tag to set leader elbow position of.</param>
            <param name="location">The new location for the leader elbow.</param>
            <search>
            Tag, Tag.Location
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Roof">
            <summary>
            Wrapper class for roofs.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Roof.AddSplitLineWithElevation(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Curve,System.Double)">
            <summary>
            This node will add a split line to the given roof with supplied line and elevation.
            </summary>
            <param name="roof">The roof to split.</param>
            <param name="curve">The geometry curve to use.</param>
            <param name="elevation">The elevation to go to.</param>
            <returns name="result">The result..</returns>
            <search>
            Element.CreateParts, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Roof.AddPoint(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This node will add a point to the given roof.
            </summary>
            <param name="roof">The roof to add shape editing points to.</param>
            <param name="point">The points to add.</param>
            <returns name="result">The result..</returns>
            <search>
            Roof.AddPoint, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.CurtainGridLine">
            <summary>
            Wrapper class for curtain gridlines.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGridLine.FullCurve(Revit.Elements.Element)">
            <summary>
            This node will retrieve the geometric curve from the curtain wall.
            </summary>
            <param name="curtainGridLine">The curtain gridline to get data from.</param>
            <returns name="fullCurve">The full geometric curve</returns>
            <search>
            CurtainGridLine.FullCurve, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGridLine.AllSegmentCurves(Revit.Elements.Element)">
            <summary>
            This node will retrieve the geometric curve segments from the curtain wall.
            </summary>
            <param name="curtainGridLine">The curtain gridline to get data from.</param>
            <returns name="AllSegmentCurves">The segments that make up the curtain grid.</returns>
            <search>
            CurtainGridLine.FullCurve, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGridLine.RemoveSegment(Revit.Elements.Element,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Curve})">
            <summary>
            This node will remove the given curve segments from the curtain grid line.
            </summary>
            <param name="curtainGridLine">The curtain gridline to remove segments from.</param>
            <param name="curves">The curves that represent the grid segment to remove.</param>
            <returns name="curtainGridLine">The curtain grid that wsa supplied.</returns>
            <search>
            CurtainGridLine.RemoveSegment, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGridLine.ExistingSegmentCurves(Revit.Elements.Element)">
            <summary>
            This node will retrieve the geometric existing curve segments from the curtain wall.
            </summary>
            <param name="curtainGridLine">The curtain gridline to get data from.</param>
            <returns name="existingSegmentCurves">The segments that make up the curtain grid.</returns>
            <search>
            CurtainGridLine.ExistingSegmentCurves, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGridLine.SkippedSegmentCurves(Revit.Elements.Element)">
            <summary>
            This node will retrieve the geometric skipped curve segments from the curtain wall.
            </summary>
            <param name="curtainGridLine">The curtain gridline to get data from.</param>
            <returns name="skippedSegmentCurves">The segments that make up the curtain grid.</returns>
            <search>
            CurtainGridLine.SkippedSegmentCurves, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Dimension">
            <summary>
            Wrapper class for dimensions.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.GetCurve(Revit.Elements.Dimension)">
            <summary>
            This node will get the dimension's line.
            </summary>
            <param name="dimension">The dimension to obtain the curve from.</param>
            <returns name="dimensionLine">The curve representing the dimension.</returns>
            <search>
            Dimension.GetCurve, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.Segments(System.Collections.Generic.List{Revit.Elements.Dimension})">
            <summary>
            This node will return the segments comprising the multi segment dimension.
            </summary>
            <param name="dimension">Multi segment dimension.</param>
            <returns name="segmentArray">The individual members.</returns>
            <search>
            dimension.Segments
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.SetAboveValue(Revit.Elements.Dimension,System.Collections.Generic.List{System.String})">
            <summary>
            This node will try to set the above value for the dimensions. This will work for either single segment dimensions or all segments of a multi-segment dimension.
            </summary>
            <param name="dimension">Dimension to set</param>
            <param name="aboveValue">Value to set.</param>
            <returns name="set">Succesfully set.</returns>
            <returns name="notSet">Not so succesfully set.</returns>
            <search>
            dimension.SetAboveValue
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.SetBelowValue(Revit.Elements.Dimension,System.Collections.Generic.List{System.String})">
            <summary>
            This node will try to set the below value for the dimensions. This will work for either single segment dimensions or all segments of a multi-segment dimension.
            </summary>
            <param name="dimension">Dimension to set</param>
            <param name="belowValue">Value to set.</param>
            <returns name="set">Succesfully set.</returns>
            <returns name="notSet">Not so succesfully set.</returns>
            <search>
            dimension.SetBelowValue
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.GetReferenceElements(Revit.Elements.Dimension)">
            <summary>
            This node will retrieve the reference elements of the dimension. Will not work with multi segment dimensions.
            </summary>
            <param name="dimension">Dimension to get elements from.</param>
            <returns name="referenceElements">The reference elements.</returns>
            <search>
            dimension.GetReferenceElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.CenterTextOnLine(Revit.Elements.Dimension)">
            <summary>
            This node will center the dimension's text on the line. More of a proof of concept.
            </summary>
            <param name="dimension">The dimension to center text on line for.</param>
            <returns name="dimension">The dimension.</returns>
            <search>
            Dimension.CenterTextOnLine
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.SetTextLocation(Revit.Elements.Dimension,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point})">
            <summary>
            This node will try to set the text location for the given dimensions. This will work for either single segment dimensions or all segments of a multi-segment dimension.
            </summary>
            <param name="dimension">Dimension to set</param>
            <param name="locationPoint">Value to set.</param>
            <search>
            dimension.SetTextLocation
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.NumberOfSegments(System.Collections.Generic.List{Revit.Elements.Dimension})">
            <summary>
            This node will return the number of segments comprising the multi segment dimension.
            </summary>
            <param name="dimension">Multi segment dimension.</param>
            <returns name="numberOfSegments">The amount of segments.</returns>
            <search>
            dimension.Segments
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.Origin(System.Collections.Generic.List{Revit.Elements.Dimension})">
            <summary>
            This node will return the origin of the single segment dimension.
            </summary>
            <param name="dimension">Single segment dimension.</param>
            <returns name="origin">The dimension origin.</returns>
            <search>
            dimension.Origin
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.TextPosition(System.Collections.Generic.List{Revit.Elements.Dimension})">
            <summary>
            This node will return the text position of the single segment dimension.
            </summary>
            <param name="dimension">Single segment dimension.</param>
            <returns name="texPosition">The dimension text position.</returns>
            <search>
            dimension.TextPosition
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Dimension.ValueString(System.Collections.Generic.List{Revit.Elements.Dimension})">
            <summary>
            This node will return the value (string) of the single segment dimension.
            </summary>
            <param name="dimension">Single segment dimension.</param>
            <returns name="valueString">The dimension value as a string.</returns>
            <search>
            dimension.TextPosition
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.CurtainPanel">
            <summary>
            Wrapper class for curtain panels.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainPanel.IsolateInView(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will isolate the given curtain wall panels in the active view. 
            </summary>
            <param name="curtainPanels">The curtain panels to isolate.</param>
            <returns name="curtainPanels">The isolated curtain panels.</returns>
            <search>
            copy
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.ElevationMarker">
            <summary>
            Wrapper class for elevation markers.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.ElevationMarker.CreateElevationMarker(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point},System.Int32,Revit.Elements.Element)">
            <summary>
            This node will create an empty elevation marker at the given points. 
            </summary>
            <param name="location">The location of the view.</param>
            <param name="scaleFactor">The scale factor of the view in integer value. E.g. "96"</param>
            <param name="viewFamilyType">The view family type you wish to use.</param>
            <returns name="elevationMarker">The created elevation marker.</returns>
            <search>
            viewport, addview,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.ElevationMarker.CreateElevationByMarkerIndex(Revit.Elements.Element,Revit.Elements.Element,System.Collections.Generic.List{System.Int32})">
            <summary>
            This node will add evelations on each side of the marker chosen. Typically 0-3. 
            </summary>
            <param name="elevationMarker">The marker to host elevations on.</param>
            <param name="planView">Plan view to do this stuff to.</param>
            <param name="index">This is where the view appears.</param>
            <returns name="Result">The result</returns>
            <search>
            viewport, addview,rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.RevitLink">
            <summary>
            Wrapper class for revit links.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.RevitLink.GetDocument(Revit.Elements.Element)">
            <summary>
            This node will obtain the selected link's document.
            </summary>
            <param name="linkInstance">The link to get document from.</param>
            <returns name="Document">The document.</returns>
            <search>
             rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Room">
            <summary>
            Wrapper class for rooms.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Room.CenterRoom(System.Collections.Generic.List{Revit.Elements.Room})">
            <summary>
            This node will center the room.
            </summary>
            <param name="room">The room to center.</param>
            <returns name="room">The room.</returns>
            <search>
            roomtag, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Room.CenterRoom2(Revit.Elements.Room)">
            <summary>
            This node will center the room.
            </summary>
            <param name="room">The room to center.</param>
            <returns name="room">The room.</returns>
            <search>
            roomtag, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Room.IntersectingElementsInRoom(Revit.Elements.Room,Revit.Elements.Category)">
            <summary>
            This node will center the room.
            </summary>
            <param name="room">The room to center.</param>
            <param name="category">The room to center.</param>
            <returns name="elements">The room.</returns>
            <search>
            roomtag, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.DimensionType">
            <summary>
            Wrapper class for dimension type.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.DimensionType.UsesProjectSettings(System.Collections.Generic.List{Revit.Elements.DimensionType})">
            <summary>
            Dtermine if the given dimension type uses project (default) settings.
            </summary>
            <param name="dimensionType">The dimension type the unit format options from.</param>
            <returns name="bool">A boolean mask to filter with.</returns>
            <search>
            dimensiontype
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.ReferencePlane">
            <summary>
            Wrapper class for reference planes.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.ReferencePlane.GetCurvesInView(System.Collections.Generic.List{Revit.Elements.Element},Revit.Elements.Views.View)">
            <summary>
            This node will get the underlying curve of the reference plane in a given view.
            </summary>
            <param name="referencePlane">The reference plane to get curves from.</param>
            <param name="view">The view to obtain the curves in.</param>
            <returns name="curve">The room that is tagged.</returns>
            <search>
            referenceplane,referenceplane.getcurvesinview
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Parts">
            <summary>
            Wrapper class for Parts.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Parts.DivideParts(Revit.Elements.Element,System.Collections.Generic.List{Revit.Elements.ReferencePlane})">
            <summary>
            This node will divide the given parts by reference planes.
            </summary>
            <param name="part">The part to divide.</param>
            <param name="referencePlane">The reference plane to use for the division.</param>
            <returns name="Parts">The created parts from the given element.</returns>
            <search>
            Parts.DivideParts, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Parts.GetSourceElement(Revit.Elements.Element)">
            <summary>
            Gets the collection of elements from which the parts were created.
            </summary>
            <param name="part">The part to get the element from.</param>
            <returns name="sourceElement">The created parts from the given element.</returns>
            <search>
            Parts.GetSourceElement, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Element">
            <summary>
            Wrapper class for Element.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetNull">
            <summary>
                Get Null
            </summary>
            <returns></returns>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.CreateParts(Revit.Elements.Element)">
            <summary>
            This node will convert the given elements to parts.
            </summary>
            <param name="element">The element to convert to parts.</param>
            <returns name="Parts">The created parts from the given element.</returns>
            <search>
            Element.CreateParts
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetParameterValueByNameTypeOrInstance(Revit.Elements.Element,System.String)">
            <summary>
            This node will get the parameter as instance or type.
            </summary>
            <param name="element">The element to get parameter from.</param>
            <param name="parameterName">The parameter name.</param>
            <returns name="value">The parameter value.</returns>
            <search>
             TypeOrInstance
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.SetParameterByNameTypeOrInstance(Revit.Elements.Element,System.String,System.Object)">
            <summary>
            Set one of the element's parameters. Instance if it is instance or type if type.
            </summary>
            <param name="element">The element to set parameter to.</param>
            <param name="parameterName">The parameter name.</param>
            <param name="value">The value to set.</param>
            <returns name="element">The element.</returns>
            <search>
            TypeOrInstance
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetParameterByNameInDocument(Autodesk.Revit.DB.Document,Revit.Elements.Element,System.String)">
            <summary>
            Get one of the element's parameters in a given document.
            </summary>
            <param name="document">The document to set it in.</param>
            <param name="element">The element to set parameter to.</param>
            <param name="parameterName">The parameter name.</param>
            <returns name="val">The element's parameter.</returns>
            <search>
             
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetIntersectingElementsOfCategory(Revit.Elements.Element,Revit.Elements.Category)">
            <summary>
            This will take a given element and category and grab the intersecting elements of that category.
            </summary>
            <param name="element">The element to run intersections against.</param>
            <param name="category">The category to check.</param>
            <returns name="elements">The intersecting elements.</returns>
            <search>
             IntersectingElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetParameterValueByNameCaSeiNSeNSiTiVe(Revit.Elements.Element,System.String)">
            <summary>
            This node will get a parameter value by search string, regardless of case of the search string. Also accounts for misspellings. 
            Note: If the parameter name appears multiple times it will retrieve the first one that it finds.
            </summary>
            <param name="element">The element to get parameter from.</param>
            <param name="parameterName">The parameter name.</param>
            <returns name="value">The parameter value.</returns>
            <search>
            CaseInsensitive
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.SetParameterValueByNameCaSeiNSeNSiTiVe(Revit.Elements.Element,System.String,System.Object)">
            <summary>
            This node will set a parameter value by search string, regardless of case of the search string. Also accounts for misspellings. 
            Note: If the parameter name appears multiple times it will retrieve the first one that it finds.
            </summary>
            <param name="element">The element to get parameter from.</param>
            <param name="parameterName">The parameter name.</param>
            <param name="value">The parameter value.</param>
            <returns name="element">The element that had parameters set.</returns>
            <search>
             CaseInsensitive
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.GetIntersectingElementsOfCategoryLinkOption(Revit.Elements.Element,Revit.Elements.Category,Revit.Elements.Element)">
            <summary>
            This will take a given element and category and grab the intersecting elements of that category.
            </summary>
            <param name="element">The element to run intersections against.</param>
            <param name="sourceInstance">Use this input if the elements are from a link! If they are not, leave it blank.</param>
            <param name="category">The category to check.</param>
            <returns name="elements">The intersecting elements.</returns>
            <search>
             IntersectingElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.IsHiddenInView(System.Collections.Generic.List{Revit.Elements.Element},Revit.Elements.Views.View)">
            <summary>
            This node will report whether or not the given element is hidden in given views.
            </summary>
            <param name="element">The element to check.</param>
            <param name="view">The views to check in.</param>
            <returns name="bool">Is it hidden?</returns>
            <search>
             IsVisible
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.DependentElements(Revit.Elements.Element)">
            <summary>
            This node will report what elements depend on the input element. Useful for determining safe deletion.(Available Revit 2018.1+).
            </summary>
            <param name="element">The element to check.</param>
            <returns name="dependentElements">The dependent elements.</returns>
            <search>
             DependentElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.DependentElementsOfCategory(Revit.Elements.Element,Revit.Elements.Category)">
            <summary>
            This node will report what elements depend on the input element. Useful for determining safe deletion.(Available Revit 2018.1+).
            </summary>
            <param name="element">The element to check.</param>
            <param name="category">The category to use to filter the elements.</param>
            <returns name="dependentElements">The dependent elements.</returns>
            <search>
             DependentElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.JoinedElements(Revit.Elements.Element)">
            <summary>
            This node will report what elements are joined to the input element.
            </summary>
            <param name="element">The element to check.</param>
            <returns name="joinedElements">The joined elements.</returns>
            <search>
             Element.GetJoinedElements,JoinedElements
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Element.SetPinnedStatus(Revit.Elements.Element,System.Boolean)">
            <summary>
            This node will change the pinned status of an element.
            </summary>
            <param name="element">The element to change the status of.</param>
            <param name="status">The pinned status. True = pinned, False = not pinned.</param>
            <returns name="element">The elements.</returns>
            <search>
             Element.SetPinnedStatus
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.FamilyInstance">
            <summary>
            Wrapper class for FamilyInstance.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.FamilyInstance.Room(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will report the room the family instance resides in, (if available).
            </summary>
            <param name="instance">The family instance to obtain room info from.</param>
            <returns name="Room">The room in which the instance is located (during the last phase of the project).</returns>
            <search>
            room, rhythm,element.room
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.FamilyInstance.Space(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will report the space the family instance resides in, (if available).
            </summary>
            <param name="instance">The family instance to obtain space info from.</param>
            <returns name="Space">The space in which the instance is located (during the last phase of the project).</returns>
            <search>
            space, rhythm,element.space
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.FamilyInstance.RetrieveNestedComponents(Revit.Elements.FamilyInstance)">
            <summary>
            This node will find all deeply nested components in the given family instance.
            </summary>
            <param name="instance">The family instance to retrieve deep nested components from.</param>
            <returns name="nestedComponents">The nested components.</returns>
            <search>
            nested,
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.FamilyInstance.ByRoom(System.String,Revit.Elements.Room,System.String,Revit.Elements.Category,System.String)">
            <summary>
            This node will create and place a generic model family instance at all the room locations given the room element. This will close all family documents so keep that in mind!
            </summary>
            <param name="familyTemplatePath">The family template to use.</param>
            <param name="room">The room to convert to generic model.</param>
            <param name="materialName">The material to assign to the solid. *Note - The material has to exist in the family template to work. If it does not exist nothing will be assigned.</param>
            <param name="category">The category to assign to the family. *Note - this needs to be a category that works for families. (Doors, Generic Models, etc.)</param>
            <param name="subcategory">The subcategory to assign to the solid. *Note - this needs to exist in the family template, if it does not, nothing will be changed in this regard.</param>
            <returns name="familyInstance">The family instances that were placed.</returns>
            <search>
            space, rhythm,element.space
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.CurtainGrid">
            <summary>
            Wrapper class for curtain grids.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGrid.ByWallElement(Revit.Elements.Wall)">
            <summary>
            This node will retrieve the curtain grid and U/V Gridlines from the given wall
            </summary>
            <param name="curtainWall">The curtain gridline to get data from.</param>
            <returns name="curtainGrid">The internal curtain grid.</returns>
            <returns name="uGrids">The grids in the U direction, (horizontal).</returns>
            <returns name="vGrids">The grids in the V direction, (vertical).</returns>
            <search>
            curtaingrid, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGrid.ByCurtainSystem(Revit.Elements.CurtainSystem)">
            <summary>
            This node will retrieve the curtain grid per face from the curtain system.
            </summary>
            <param name="curtainSystem">The curtain system to get data from.</param>
            <returns name="curtainGrid">The internal curtain grid.</returns>
            <search>
            curtaingrid, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGrid.UGrids(Autodesk.Revit.DB.CurtainGrid)">
            <summary>
            This node will retrieve the U gridlines from the curtain grid
            </summary>
            <param name="curtainGrid">The curtain grid to get data from.</param>
            <returns name="UGrids">The grids in the U direction, (horizontal).</returns>
            <search>
            curtaingrid, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGrid.VGrids(Autodesk.Revit.DB.CurtainGrid)">
            <summary>
            This node will retrieve the V gridlines from the curtain grid
            </summary>
            <param name="curtainGrid">The curtain grid to get data from.</param>
            <returns name="VGrids">The grids in the V direction, (horizontal).</returns>
            <search>
            curtaingrid, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.CurtainGrid.AddGridLineByPoint(Autodesk.Revit.DB.CurtainGrid,Autodesk.DesignScript.Geometry.Point,System.Boolean)">
            <summary>
            This node will add a gridline at the specified place on the curtain wall grid.
            </summary>
            <param name="curtainGrid">The curtain grid to add a gridline to.</param>
            <param name="locationPoint">XYZ location to place grid</param>
            <param name="isUGridline">Is this gridline horizontal?</param>
            <returns name="curtainGridLine">The new gridline</returns>
            <search>
            curtainwall, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.BeamSystem">
            <summary>
            Wrapper class for beam systems.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.BeamSystem.Members(Revit.Elements.Element)">
            <summary>
            Obtains the individual beams within a beam system.
            </summary>
            <param name="BeamSystem">The beam system to get information from.</param>
            <returns name="members">The individual members.</returns>
            <search>
            structural, beamsystem
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.BeamSystem.DropBeamSystem(Revit.Elements.Element)">
            <summary>
            Drops the beam system.
            </summary>
            <param name="beamSystem">The beam system to drop.</param>
            <returns name="members">The individual members.</returns>
            <search>
            structural, beamsystem
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.RoomTag">
            <summary>
            Wrapper class for room tags.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.RoomTag.TaggedRoom(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will retrieve the room that a tag is tagging.
            </summary>
            <param name="roomTag">The room tag to retrieve elements from.</param>
            <returns name="room">The room that is tagged.</returns>
            <search>
            roomtag, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.RoomTag.CenterOnRoomLocation(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will set the room tag to the same as the room location.
            </summary>
            <param name="roomTag">The room tag to set.</param>
            <returns name="roomTag">The room tag.</returns>
            <search>
            roomtag, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.TextNote">
            <summary>
            Wrapper class for textnotes.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.TextNote.ToUpper(Revit.Elements.Element)">
            <summary>
            This node will convert the text note to upper with formatting.
            </summary>
            <param name="textNote">The text note to convert.</param>
            <returns name="textNote">The converted text note.</returns>
            <search>
            textnote, toupper, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.TextNote.ToLower(Revit.Elements.Element)">
            <summary>
            This node will convert the text note to lower with formatting.
            </summary>
            <param name="textNote">The text note to convert.</param>
            <returns name="textNote">The converted text note.</returns>
            <search>
            textnote, tolower, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Sheet">
            <summary>
            Wrapper class for sheets.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Sheet.GetViewportsAndViews(Revit.Elements.Views.Sheet)">
            <summary>
            This node will obtain viewports, views and schedules from a given sheet.
            </summary>
            <param name="sheet">The sheet to get viewports from.</param>
            <returns name="viewports">The viewports on the sheet.</returns>
            <returns name="views">The views on the sheet.</returns>
            <returns name="schedules">The schedules on the sheet.</returns>
            <search>
            viewport, schedules,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Sheet.Create(Revit.Elements.FamilyType)">
            <summary>
            Creates a new sheet.
            </summary>
            <param name="titleblock">The titleblock to use.</param>
            <returns name="Sheet">The newly created sheet.</returns>
            <search>
            sheet,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Sheet.Titleblock(Revit.Elements.Views.Sheet)">
            <summary>
            This node will grab the titleblock from the given sheet.
            </summary>
            <param name="viewSheet">The sheet to get titleblock from.</param>
            <returns name="titleblock">The sheet's titleblock.</returns>
            <search>
            sheet, sheets, titleblock
            </search>
        </member>
        <member name="T:Rhythm.Revit.Elements.Viewport">
            <summary>
            Wrapper class for viewports.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Elements.Viewport.Create(Revit.Elements.Views.Sheet,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This node will place the given view on the given sheet, if possible. For floor plan views: They cannot be on any other sheets. Now supports schedules! 
            </summary>
            <param name="sheet">The sheet to place views on.</param>
            <param name="view">The view to place.</param>
            <param name="location">The location of the view.</param>
            <returns name="Result">The result</returns>
            <search>
            viewport, addview,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Viewport.LocationData(Revit.Elements.Element)">
            <summary>
            This node will obtain the box location data from the provided viewport.
            </summary>
            <param name="viewport">Viewport to obtain data from.</param>
            <returns name="bBox">The bounding box of the viewport.</returns>
            <returns name="boxCenter">The center of the viewport.</returns>
            <returns name="boxOutline">The outline of the viewport.</returns>
            <search>
            viewport, Viewport.LocationData,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Viewport.LabelOutline(Revit.Elements.Element)">
            <summary>
            This node will obtain the outline of the Viewport title if one is used. This is the label outline.
            </summary>
            <param name="viewport">Viewport to obtain data from.</param>
            <returns name="labelOutline">The label outline of the viewport.</returns>
            <search>
            viewport, Viewport.LavelOutline, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Viewport.GetView(Revit.Elements.Element)">
            <summary>
            This node will obtain the view from the given viewport.
            </summary>
            <param name="viewport">Viewport to obtain view from.</param>
            <returns name="view">The view that belongs to the viewport.</returns>
            <search>
            viewport, location,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Elements.Viewport.SetLocationBasedOnOther(Revit.Elements.Element,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will set the child viewports box center given the parent viewport.
            </summary>
            <param name="parentViewport">Viewport to get location from.</param>
            <param name="childViewports">Viewports to set to location collected.</param>
            <returns name="childViewports">The viewports you moved.</returns>
            <search>
            viewport
            </search>
        </member>
        <member name="T:Rhythm.Revit.Ribbon.RibbonTab">
            <summary>
            Wrapper class for ribbon stuff.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.RibbonTab.SetName(Autodesk.Windows.RibbonTab,System.String)">
            <summary>
            This will rename a tab given a new name.
            </summary>
            <param name="tab">The tab.</param>
            <param name="name">The new name.</param>
            <returns name="result">The result..</returns>
            <search>
            Ribbon.RenameTab
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.RibbonTab.SetVisibility(Autodesk.Windows.RibbonTab,System.Boolean)">
            <summary>
            This will hide or show the given tab.
            </summary>
            <param name="tab">The tab to modify.</param>
            <param name="toggle">True or false for tab visibility.</param>
            <returns name="result">The result..</returns>
            <search>
            Ribbon.RenameTab
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.RibbonTab.SetEnabled(Autodesk.Windows.RibbonTab,System.Boolean)">
            <summary>
            This will enable or disable the given tab.
            </summary>
            <param name="tab">The tab name to modify.</param>
            <param name="toggle">True or false for tab visibility.</param>
            <returns name="result">The result..</returns>
            <search>
            Ribbon.RenameTab
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.RibbonTab.GetTabs(System.Boolean)">
            <summary>
            This will give you access to all tabs.
            </summary>
            <param name="toggle">True or false to refresh collection.</param>
            <returns name="ribbonTabs">The ribbon tabs in the application.</returns>
            <search>
            Ribbon.RenameTab
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.RibbonTab.Name(Autodesk.Windows.RibbonTab)">
            <summary>
            This will get the tab's name.
            </summary>
            <param name="tab">The original tab name.</param>
            <returns name="name">The result..</returns>
            <search>
            Ribbon.RenameTab
            </search>
        </member>
        <member name="T:Rhythm.Revit.Ribbon.Modifiers">
            <summary>
            Wrapper class for ribbon stuff.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.Modifiers.Rotate(System.Int32)">
            <summary>
            This will rotate your ribbon. Seriously.
            </summary>
            <param name="rotation">The amount to rotate the ribbon.</param>
            <returns name="rotation">The rotated amount.</returns>
            <search>
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.Modifiers.SetFont(System.String)">
            <summary>
            This will set the font on your ribbon.
            </summary>
            <param name="fontName">The font to use.</param>
            <returns name="fontName">Thefont used.</returns>
            <search>
            </search>
        </member>
        <member name="M:Rhythm.Revit.Ribbon.Modifiers.SetColor(DSCore.Color)">
            <summary>
            This will set the color of your ribbon.
            </summary>
            <param name="color">The color to use</param>
            <returns name="color">The rotated amount.</returns>
            <search>
            Categories.ProjectionLineweight
            </search>
        </member>
        <member name="T:Rhythm.Revit.Selection.Collector">
            <summary>
            Wrapper class for textnotes.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Selection.Collector.ElementsOfTypeInDocument(Autodesk.Revit.DB.Document,System.Type)">
            <summary>
            This node will collect all elements of type from given document.
            </summary>
            <param name="document">The document to collect from.</param>
            <param name="elementType">The element type to collect.</param>
            <returns name="element">The elements.</returns>
            <search>
            All Elements of Type in Document
            </search>
        </member>
        <member name="T:Rhythm.Revit.Tools.Batch">
            <summary>
            Wrapper class for batchers.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Tools.Batch.UpgradeFamilies(System.String)">
            <summary>
            This tool with batch upgrade all the Revit families in a directory and delete the backup files that are generated.
            </summary>
            <param name="directoryPath">The directory to read for ALL families. Including subdirectories.</param>
            <returns name="Succesfully Upgraded">Files that were upgraded.</returns>
            <returns name="Not So Succesfully Upgraded">Files that were not upgraded.</returns>
            <search>
            Application.OpenDocumentFile, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Tools.Element">
            <summary>
            Wrapper class for animators
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Tools.Element.AnimateNumericParameter(System.Collections.Generic.List{Revit.Elements.Element},System.String,System.Double,System.Double,System.Int32,System.String,Revit.Elements.Element)">
            <summary>
            Animate a numeric parameter of an element. This will export images of the parameter, then revert the element back to where it was. Also adds text to comments to prevent infinite loops.Clear this comment for subsequent runs.
            Inspired by the Bad Monkeys Team.
            </summary>
            <param name="element">The element to set parameter to.</param>
            <param name="parameterName">The parameter name.</param>
            <param name="startValue">The value to set.</param>
            <param name="endValue">The value to set.</param>
            <param name="iterations">The number of images.</param>
            <param name="directoryPath">Where to save the images.</param>
            <param name="view">The view to export from.</param>
            <returns name="element">The element.</returns>
            <search>
             rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Tools.Element.AnimateColor(System.Collections.Generic.List{Revit.Elements.Element},DSCore.Color,DSCore.Color,System.Int32,System.String,Revit.Elements.Element)">
            <summary>
            Animate the color of an element. This will export images of the element, then revert the element back to where it was.
            Inspired by the Bad Monkeys team.
            </summary>
            <param name="element">The element to set color to.</param>
            <param name="startColor">The start color.</param>
            <param name="endColor">The end color.</param>
            <param name="iterations">Numnber of images.</param>
            <param name="directoryPath">Where to save the images.</param>
            <param name="view">View to export from.</param>
            <returns name="element">The element.</returns>
            <search>
             rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Tools.Element.AnimateTransparency(System.Collections.Generic.List{Revit.Elements.Element},System.Int32,System.Int32,System.Int32,System.String,Revit.Elements.Element)">
            <summary>
            Animate the transparency of an element. This will export images of the element, then revert the element back to where it was.
            Inspired by the Bad Monkeys team.
            </summary>
            <param name="element">The element to set transparency to.</param>
            <param name="startPercentage">The transparency start percent.</param>
            <param name="endPercentage">The transparency end percent.</param>
            <param name="iterations">Numnber of images.</param>
            <param name="directoryPath">Where to save the images.</param>
            <param name="view">View to export from.</param>
            <returns name="element">The element.</returns>
            <search>
             rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Application.Application">
            <summary>
            Wrapper class for application level nodes.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Application.Application.OpenDocumentFile(System.String,System.Boolean,System.Boolean)">
            <summary>
            This node will open the given file in the background.
            </summary>
            <param name="filePath">The file to obtain document from.</param>
            <param name="audit">Choose whether or not to audit the file upon opening. (Will run slower with this)</param>
            <param name="detachFromCentral">Choose whether or not to detach from central upon opening. Only for RVT files. </param>
            <returns name="Document">The document.</returns>
            <search>
            Application.OpenDocumentFile, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Application.Application.CloseDocument(Autodesk.Revit.DB.Document,System.Boolean)">
            <summary>
            This node will close the given document with the option to save.
            </summary>
            <param name="document">The document to close.</param>
            <param name="save">Do you want to save?</param>
            <returns name="result">Did it work?</returns>
            <search>
            Application.CloseDocument, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Application.Document">
            <summary>
            Wrapper class for document nodes.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Application.Document.CopyElementsFromLinkedDocument(Autodesk.Revit.DB.Document,Revit.Elements.Element,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will copy the given elements from the given linked document into the active document.
            </summary>
            <param name="sourceDocument">The document to copy from.</param>
            <param name="sourceInstance">The instance of the link to copy from.</param>
            <param name="elements">The elements to copy.</param>
            <returns name="newElements">The copied elements.</returns>
            <search>
            copy
            </search>
        </member>
        <member name="M:Rhythm.Revit.Application.Document.CopyElementsFromDocument(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            This node will copy the given elements from the given document into the active document.
            </summary>
            <param name="sourceDocument">The document to copy from.</param>
            <param name="elements">The elements to copy.</param>
            <returns name="newElements">The copied elements.</returns>
            <search>
            copy
            </search>
        </member>
        <member name="M:Rhythm.Revit.Application.Document.SetStartingView(Autodesk.Revit.DB.Document,Revit.Elements.Element)">
            <summary>
            This node will set the starting view of the document, given the view element.
            </summary>
            <param name="document">The document to do this to.</param>
            <param name="view">The view to set.</param>
            <returns name="result">The result.</returns>
            <search>
            startingView
            </search>
        </member>
        <member name="T:Rhythm.Revit.Views.Sheet">
            <summary>
            A Revit ViewSheet
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Views.Sheet.PackViews(Revit.Elements.Element,System.Collections.Generic.IEnumerable{Revit.Elements.Views.View})">
            <summary>
            This node will attempt to pack the given views on a sheet. For views that do not fit it will output a list of them.
            </summary>
            <param name="sheet">The sheet to add views to.</param>
            <param name="views">The views to try to add.</param>
            <returns name="success">Views that were added.</returns>
            <returns name="fail">Views that did not fit within the outline of the sheet.</returns>
            <search>
            Sheet.AddViews,Pack
            </search>
        </member>
        <member name="T:Rhythm.Revit.Views.View">
            <summary>
            Wrapper class for view.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Views.View.ConvertToIndependent(Revit.Elements.Element)">
            <summary>
            This node will convert a dependent view to an independent.
            </summary>
            <param name="dependentView">The view to convert to independent.</param>
            <returns name="independentView">The overidden view.</returns>
            <search>
            view, dependent,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.GetCropRegionElement(Revit.Elements.Element)">
            <summary>
            This node will obtain the crop region element from the view.
            </summary>
            <param name="view">The view to obtain the crop region element from.</param>
            <returns name="cropRegionElement">The crop region as an element.</returns>
            <search>
            crop region,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.SetElementProjectionLineweight(Revit.Elements.Element,Revit.Elements.Element,System.Int32)">
            <summary>
            This node will override the given element's projection lineweight in given view.
            </summary>
            <param name="view">The view to set the overrides in.</param>
            <param name="element">The element to override.</param>
            <param name="lineweight">The lineweight to use.</param>
            <returns name="element">The crop region as an element.</returns>
            <search>
            crop region,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.GetFilterVisibility(Revit.Elements.Element,Revit.Elements.Element)">
            <summary>
            This node will supply the visibility of the given filter in given view.
            </summary>
            <param name="view">The view to obtain filter visibility from.</param>
            <param name="viewFilter">The view filter.</param>
            <returns name="bool">The visibility value.</returns>
            <search>
            view, dependent,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.ParentView(Revit.Elements.Element)">
            <summary>
            Retrieve the input dependent view's parent, (if available).
            </summary>
            <param name="view">The view to get parent of.</param>
            <returns name="parentView">The parent view.</returns>
            <search>
            dependent, parent, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.Origin(Revit.Elements.Element)">
            <summary>
            Retrieve the input view's origin, (if available).
            </summary>
            <param name="view">The view to get origin of.</param>
            <returns name="origin">The origin of the view. Also, the origin of a plan view is not meaningful.</returns>
            <search>
            dependent, parent, rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.GetWorksetVisibility(Revit.Elements.Element,System.Collections.Generic.List{System.Int32})">
            <summary>
            This node will supply the visibility of the given workset in given view.
            </summary>
            <param name="view">The view to obtain workset visibility from.</param>
            <param name="worksetId">The workset element id as int.</param>
            <returns name="result">The workset visibility.</returns>
            <search>
            view, workset.Visible
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.View.SetCropRegion(Revit.Elements.Element,Autodesk.DesignScript.Geometry.BoundingBox)">
            <summary>
            This will attempt to set the view's crop region given a bounding box.
            </summary>
            <param name="view">The view to set the section box to.</param>
            <param name="bBox">The bounding box to use.</param>
            <returns name="success">The views that worked.</returns>
            <returns name="failed">The views that failed.</returns>
            <search>
            cropregion, crop, rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Views.View3D">
            <summary>
            Wrapper class for 3d views.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Views.View3D.SetSectionBox(Revit.Elements.Element,Autodesk.DesignScript.Geometry.BoundingBox)">
            <summary>
            This node will set the given 3d view's section box.
            </summary>
            <param name="view3D">The 3D view to set the section box for.</param>
            <param name="bBox">The boudning box to use.</param>
            <returns name="success">The views that worked.</returns>
            <returns name="failed">The views that failed.</returns>
            <search>
            view, dependent,rhythm
            </search>
        </member>
        <member name="T:Rhythm.Revit.Views.ViewSection">
            <summary>
            Wrapper class for sections.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewSection.OverrideCrop(Revit.Elements.Element,System.Int32)">
            <summary>
            This node will override the crop region of the given section view based on the pen weight provided.
            Slower but more reliable version that uses transaction rollback to isolated the crop region element.
            </summary>
            <param name="viewSection">The plan view to rotate</param>
            <param name="lineWeight">The lineweight to override to, (1-16)</param>
            <returns name="viewSection">The overidden view.</returns>
            <search>
            overridecrop
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewSection.OverrideCropVersion2(Revit.Elements.Element,System.Int32)">
            <summary>
            This node will override the crop region of the given section view based on the pen weight provided. 
            This is the faster version that works with interior elevations.
            </summary>
            <param name="viewSection">The plan view to rotate</param>
            <param name="lineWeight">The lineweight to override to, (1-16)</param>
            <returns name="viewSection">The overidden view.</returns>
            <search>
            overridecrop
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewSection.LocationPoint(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Retrieve the input view's origin, (if available).
            </summary>
            <param name="view">The view to get origin of.</param>
            <returns name="locationPoint">The origin of the view. Also, the origin of a plan view is not meaningful.</returns>
            <search>
            viewsection.locationpoint
            </search>
        </member>
        <member name="T:Rhythm.Revit.Views.ViewPlan">
            <summary>
            Wrapper class for plans.
            </summary>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewPlan.GetOutline(Revit.Elements.Element)">
            <summary>
            This node will get the bounds of the view in paper space (in feet).
            </summary>
            <param name="view">The view to get outline from.</param>
            <returns name="outline">The bounds of the view in paper space (in feet).</returns>
            <search>
            view, outline,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewPlan.GetCropBox(Revit.Elements.Element)">
            <summary>
            This node will get the bounds of the view in paper space (in feet).
            </summary>
            <param name="viewPlan">The plan view to get outline from.</param>
            <returns name="cropBox">The cropBox.</returns>
            <returns name="cropBoxCurves">The curves of the crop region.</returns>
            <search>
            view, outline,rhythm
            </search>
        </member>
        <member name="M:Rhythm.Revit.Views.ViewPlan.Rotate(Revit.Elements.Element,Revit.Elements.ModelCurve,System.Double)">
            <summary>
            This node will attempt to rotate a plan view into a 3D view. Use at your own risk!
            </summary>
            <param name="viewPlan">The plan view to rotate</param>
            <param name="rotationLine">The line to rotate along.</param>
            <param name="inputAngle">The plan view to get outline from.</param>
            <returns name="cropBox">The cropBox.</returns>
            <search>
            view, outline,rhythm
            </search>
        </member>
        <member name="M:Rhythm.FamilyUpgradeForm.#ctor(System.String,System.String,System.String,System.Int32)">
            <summary>
            Set up progress bar form and immediately display it modelessly.
            </summary>
            <param name="caption">Form caption</param>
            <param name="format">Progress message string</param>
            <param name="toolTitle">Name of the tool.</param>
            <param name="max">Number of elements to process</param>
        </member>
        <member name="F:Rhythm.FamilyUpgradeForm.components">
            <summary>
            Required designer variable.
            </summary>
        </member>
        <member name="M:Rhythm.FamilyUpgradeForm.Dispose(System.Boolean)">
            <summary>
            Clean up any resources being used.
            </summary>
            <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        </member>
        <member name="M:Rhythm.FamilyUpgradeForm.InitializeComponent">
            <summary>
            Required method for Designer support - do not modify
            the contents of this method with the code editor.
            </summary>
        </member>
        <member name="T:Rhythm.Properties.Resources">
            <summary>
              A strongly-typed resource class, for looking up localized strings, etc.
            </summary>
        </member>
        <member name="P:Rhythm.Properties.Resources.ResourceManager">
            <summary>
              Returns the cached ResourceManager instance used by this class.
            </summary>
        </member>
        <member name="P:Rhythm.Properties.Resources.Culture">
            <summary>
              Overrides the current thread's CurrentUICulture property for all
              resource lookups using this strongly typed resource class.
            </summary>
        </member>
        <member name="M:Rhythm.DefaultProgressForm.#ctor(System.String,System.String,System.String,System.Int32)">
            <summary>
            Set up progress bar form and immediately display it modelessly.
            </summary>
            <param name="caption">Form caption</param>
            <param name="format">Progress message string</param>
            <param name="toolTitle">Name of the tool.</param>
            <param name="max">Number of elements to process</param>
        </member>
        <member name="F:Rhythm.DefaultProgressForm.components">
            <summary>
            Required designer variable.
            </summary>
        </member>
        <member name="M:Rhythm.DefaultProgressForm.Dispose(System.Boolean)">
            <summary>
            Clean up any resources being used.
            </summary>
            <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        </member>
        <member name="M:Rhythm.DefaultProgressForm.InitializeComponent">
            <summary>
            Required method for Designer support - do not modify
            the contents of this method with the code editor.
            </summary>
        </member>
        <member name="T:Rhythm.Utilities.StringComparisonUtilities">
            <summary>
            
            </summary>
        </member>
        <member name="M:Rhythm.Utilities.StringComparisonUtilities.Compute(System.String,System.String)">
            <summary>
            
            </summary>
            <param name="s"></param>
            <param name="t"></param>
            <returns></returns>
        </member>
        <member name="T:Nuclex.Game.Packing.CygonRectanglePacker">
            <summary>Packer using a custom algorithm by Markus 'Cygon' Ewald</summary>
            <remarks>
              <para>
                Algorithm conceived by Markus Ewald (cygon at nuclex dot org), though
                I'm quite sure I'm not the first one to come up with it :)
              </para>
              <para>
                The algorithm always places rectangles as low as possible in the packing
                area. So, for any new rectangle that is to be added, the packer has to
                determine the X coordinate at which the rectangle can have the lowest
                overall height without intersecting any other rectangles.
              </para>
              <para>
                To quickly discover these locations, the packer uses a sophisticated
                data structure that stores the upper silhouette of the packing area. When
                a new rectangle needs to be added, only the silouette edges need to be
                analyzed to find the position where the rectangle would achieve the lowest
                placement possible in the packing area.
              </para>
            </remarks>
        </member>
        <member name="T:Nuclex.Game.Packing.CygonRectanglePacker.SliceStartComparer">
            <summary>Compares the starting position of height slices</summary>
        </member>
        <member name="F:Nuclex.Game.Packing.CygonRectanglePacker.SliceStartComparer.Default">
            <summary>Provides a default instance for the anchor rank comparer</summary>
        </member>
        <member name="M:Nuclex.Game.Packing.CygonRectanglePacker.SliceStartComparer.Compare(Autodesk.Revit.DB.UV,Autodesk.Revit.DB.UV)">
            <summary>Compares the starting position of two height slices</summary>
            <param name="left">Left slice start that will be compared</param>
            <param name="right">Right slice start that will be compared</param>
            <returns>The relation of the two slice starts ranks to each other</returns>
        </member>
        <member name="M:Nuclex.Game.Packing.CygonRectanglePacker.#ctor(System.Double,System.Double)">
            <summary>Initializes a new rectangle packer</summary>
            <param name="packingAreaWidth">Maximum width of the packing area</param>
            <param name="packingAreaHeight">Maximum height of the packing area</param>
        </member>
        <member name="M:Nuclex.Game.Packing.CygonRectanglePacker.TryPack(System.Double,System.Double,Autodesk.Revit.DB.UV@)">
            <summary>Tries to allocate space for a rectangle in the packing area</summary>
            <param name="rectangleWidth">Width of the rectangle to allocate</param>
            <param name="rectangleHeight">Height of the rectangle to allocate</param>
            <param name="placement">Output parameter receiving the rectangle's placement</param>
            <returns>True if space for the rectangle could be allocated</returns>
        </member>
        <member name="M:Nuclex.Game.Packing.CygonRectanglePacker.tryFindBestPlacement(System.Double,System.Double,Autodesk.Revit.DB.UV@)">
            <summary>Finds the best position for a rectangle of the given dimensions</summary>
            <param name="rectangleWidth">Width of the rectangle to find a position for</param>
            <param name="rectangleHeight">Height of the rectangle to find a position for</param>
            <param name="placement">Receives the best placement found for the rectangle</param>
            <returns>True if a valid placement for the rectangle could be found</returns>
        </member>
        <member name="M:Nuclex.Game.Packing.CygonRectanglePacker.integrateRectangle(System.Double,System.Double,System.Double)">
            <summary>Integrates a new rectangle into the height slice table</summary>
            <param name="left">Position of the rectangle's left side</param>
            <param name="width">Width of the rectangle</param>
            <param name="bottom">Position of the rectangle's lower side</param>
        </member>
        <member name="F:Nuclex.Game.Packing.CygonRectanglePacker.heightSlices">
            <summary>Stores the height silhouette of the rectangles</summary>
        </member>
        <member name="T:Nuclex.Game.Packing.OutOfSpaceException">
            <summary>Insufficient space left in packing area to contain a given object</summary>
            <remarks>
              An exception being sent to you from deep space. Erm, no, wait, it's an exception
              that occurs when a packing algorithm runs out of space and is unable to fit
              the object you tried to pack into the remaining packing area.
            </remarks>
        </member>
        <member name="M:Nuclex.Game.Packing.OutOfSpaceException.#ctor">
            <summary>Initializes the exception</summary>
        </member>
        <member name="M:Nuclex.Game.Packing.OutOfSpaceException.#ctor(System.String)">
            <summary>Initializes the exception with an error message</summary>
            <param name="message">Error message describing the cause of the exception</param>
        </member>
        <member name="M:Nuclex.Game.Packing.OutOfSpaceException.#ctor(System.String,System.Exception)">
            <summary>Initializes the exception as a followup exception</summary>
            <param name="message">Error message describing the cause of the exception</param>
            <param name="inner">Preceding exception that has caused this exception</param>
        </member>
        <member name="M:Nuclex.Game.Packing.OutOfSpaceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
            <summary>Initializes the exception from its serialized state</summary>
            <param name="info">Contains the serialized fields of the exception</param>
            <param name="context">Additional environmental informations</param>
        </member>
        <member name="T:Nuclex.Game.Packing.RectanglePacker">
            <summary>Base class for rectangle packing algorithms</summary>
            <remarks>
              <para>
                By uniting all rectangle packers under this common base class, you can
                easily switch between different algorithms to find the most efficient or
                performant one for a given job.
              </para>
              <para>
                An almost exhaustive list of packing algorithms can be found here:
                http://www.csc.liv.ac.uk/~epa/surveyhtml.html
              </para>
            </remarks>
        </member>
        <member name="M:Nuclex.Game.Packing.RectanglePacker.#ctor(System.Double,System.Double)">
            <summary>Initializes a new rectangle packer</summary>
            <param name="packingAreaWidth">Width of the packing area</param>
            <param name="packingAreaHeight">Height of the packing area</param>
        </member>
        <member name="M:Nuclex.Game.Packing.RectanglePacker.Pack(System.Double,System.Double)">
            <summary>Allocates space for a rectangle in the packing area</summary>
            <param name="rectangleWidth">Width of the rectangle to allocate</param>
            <param name="rectangleHeight">Height of the rectangle to allocate</param>
            <returns>The location at which the rectangle has been placed</returns>
        </member>
        <member name="M:Nuclex.Game.Packing.RectanglePacker.TryPack(System.Double,System.Double,Autodesk.Revit.DB.UV@)">
            <summary>Tries to allocate space for a rectangle in the packing area</summary>
            <param name="rectangleWidth">Width of the rectangle to allocate</param>
            <param name="rectangleHeight">Height of the rectangle to allocate</param>
            <param name="placement">Output parameter receiving the rectangle's placement</param>
            <returns>True if space for the rectangle could be allocated</returns>
        </member>
        <member name="P:Nuclex.Game.Packing.RectanglePacker.PackingAreaWidth">
            <summary>Maximum width the packing area is allowed to have</summary>
        </member>
        <member name="P:Nuclex.Game.Packing.RectanglePacker.PackingAreaHeight">
            <summary>Maximum height the packing area is allowed to have</summary>
        </member>
        <member name="F:Nuclex.Game.Packing.RectanglePacker.packingAreaWidth">
            <summary>Maximum allowed width of the packing area</summary>
        </member>
        <member name="F:Nuclex.Game.Packing.RectanglePacker.packingAreaHeight">
            <summary>Maximum allowed height of the packing area</summary>
        </member>
    </members>
</doc>
